name: CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: build C-Teil
        working-directory: ./src
        run: make build


  unitTest_C:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: test C-Teil
        working-directory: ./src
        run: make test
      

  staticAnalysis_C:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: static analysis C-Teil
        working-directory: ./src
        run: make check
  Python-Teil:
    runs-on: ubuntu-latest

    steps:
      - name: install Python-Teil
        working-directory: ./python
        run: make install
      
      - name: test Python-Teil
        working-directory: ./python
        run: make test
      
      - name: static analysis Python-Teil
        working-directory: ./python
        run: make check

       

